package com.psychologist.financial.data.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import java.time.LocalDate
import java.time.LocalDateTime

/**
 * Room database entity for Patient
 *
 * Represents a psychologist's patient with contact information and status.
 *
 * Database Table: "patient"
 * Primary Key: id (auto-increment)
 * Indexes: phone (unique), email (unique), status + registration_date, last_appointment_date
 *
 * Constraints:
 * - name: NOT NULL, max 200 chars
 * - phone: UNIQUE, max 20 chars, nullable
 * - email: UNIQUE, max 254 chars, nullable
 * - At least one contact (phone or email) required (enforced at application layer)
 * - initial_consult_date: NOT NULL, <= today
 * - registration_date: NOT NULL, immutable (set at creation)
 * - last_appointment_date: nullable (null if no appointments yet)
 * - status: NOT NULL, default ACTIVE
 *
 * Relationships:
 * - 1 Patient : N Appointments (one-to-many)
 * - 1 Patient : N Payments (one-to-many)
 *
 * State Management:
 * - ACTIVE: Normal state, can have new appointments/payments
 * - INACTIVE: Soft-deleted, read-only (no new data)
 *
 * Usage:
 * ```kotlin
 * val patient = PatientEntity(
 *     name = "João Silva",
 *     phone = "(11) 99999-9999",
 *     email = "joao@example.com",
 *     status = PatientStatus.ACTIVE,
 *     initialConsultDate = LocalDate.now(),
 *     registrationDate = LocalDate.now()
 * )
 * ```
 *
 * @property id Unique identifier (auto-increment primary key)
 * @property name Patient full name (2-200 chars, required)
 * @property phone Contact phone number (optional, unique)
 * @property email Contact email (optional, unique)
 * @property status Patient status (ACTIVE or INACTIVE)
 * @property initialConsultDate First consultation/registration date (required)
 * @property registrationDate Record creation date (immutable)
 * @property lastAppointmentDate Most recent appointment date (auto-updated)
 * @property createdDate Timestamp when record was created (from BaseEntity)
 */
@Entity(
    tableName = "patient",
    indices = [
        // Unique indexes for contact fields
        Index(name = "idx_patient_phone", value = ["phone"], unique = true),
        Index(name = "idx_patient_email", value = ["email"], unique = true),
        // Composite index for filtering active patients by registration date
        Index(name = "idx_patient_status_regdate", value = ["status", "registration_date"]),
        // Index for "most recently active patients" query
        Index(name = "idx_patient_last_appt", value = ["last_appointment_date"], unique = false)
    ]
)
data class PatientEntity(
    /**
     * Unique identifier (primary key)
     *
     * Auto-increment generated by Room on insert.
     * Default 0 indicates unsaved entity.
     * After insert, Room assigns generated ID > 0.
     */
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    override val id: Long = 0,

    /**
     * Patient full name
     *
     * Required field, 2-200 characters.
     * Stored as TEXT in database.
     * Validation: Non-empty, no leading/trailing whitespace
     *
     * Example: "João Silva Santos"
     */
    @ColumnInfo(name = "name")
    val name: String,

    /**
     * Patient phone number
     *
     * Optional field, must be unique if provided.
     * Max 20 characters to accommodate international formats.
     * Nullable in database.
     *
     * Valid formats:
     * - (11) 99999-9999 (Brazilian mobile)
     * - +55 11 99999-9999 (International)
     * - 11999999999 (No formatting)
     *
     * Validation: ^[0-9\-\+\(\) ]{7,20}$ if provided
     * At least one of phone/email must be provided (application level)
     */
    @ColumnInfo(name = "phone")
    val phone: String? = null,

    /**
     * Patient email address
     *
     * Optional field, must be unique if provided.
     * Max 254 characters (RFC 5321).
     * Nullable in database.
     *
     * Example: "joao@example.com"
     *
     * Validation: RFC 5322 simplified pattern if provided
     * At least one of phone/email must be provided (application level)
     */
    @ColumnInfo(name = "email")
    val email: String? = null,

    /**
     * Patient status
     *
     * Enum: ACTIVE or INACTIVE
     * Stored as TEXT in database (enum name).
     * Default: ACTIVE
     *
     * State transitions:
     * - ACTIVE: Normal state, can add appointments/payments
     * - INACTIVE: Read-only (soft-deleted), prevents new data
     *
     * Use Cases:
     * - ACTIVE: Current patients receiving treatment
     * - INACTIVE: Archived/inactive patients (not shown in list by default)
     *
     * Implementation: Soft-delete pattern (no permanent deletion)
     */
    @ColumnInfo(name = "status")
    val status: String = Constants.PatientStatus.ACTIVE.name,

    /**
     * Initial consultation date
     *
     * Date of first consultation/registration.
     * Stored as TEXT (ISO 8601: YYYY-MM-DD).
     * Required, cannot be null.
     * Cannot be in future (business rule).
     *
     * Used for:
     * - Patient history tracking
     * - Filtering by registration period
     * - Audit trail
     *
     * Example: LocalDate(2025, 1, 15)
     */
    @ColumnInfo(name = "initial_consult_date")
    val initialConsultDate: LocalDate,

    /**
     * Patient registration date
     *
     * Date when patient record was created in system.
     * Stored as TEXT (ISO 8601: YYYY-MM-DD).
     * Immutable - set at creation, never updated.
     * Defaults to today if not provided.
     *
     * Used for:
     * - Record creation timestamp
     * - Filtering by registration period
     * - Audit trail
     *
     * Note: Different from initialConsultDate (which can be in past)
     *       registrationDate is always "today" when record created
     */
    @ColumnInfo(name = "registration_date")
    val registrationDate: LocalDate,

    /**
     * Most recent appointment date
     *
     * Auto-updated when new appointment created.
     * Stored as TEXT (ISO 8601: YYYY-MM-DD).
     * Nullable - null if no appointments yet.
     *
     * Used for:
     * - "Most recently active patients" query
     * - Dashboard metrics
     * - Patient activity tracking
     *
     * Updates:
     * - Set to appointment.date when appointment created
     * - Never manually updated in UI
     */
    @ColumnInfo(name = "last_appointment_date")
    val lastAppointmentDate: LocalDate? = null,

    /**
     * Creation timestamp (from BaseEntity)
     *
     * When this record was created in database.
     * Stored as TEXT (ISO 8601: YYYY-MM-DDTHH:mm:ss).
     * Immutable, set to LocalDateTime.now() at insertion.
     *
     * Used for:
     * - Audit trail (microsecond precision vs registrationDate day precision)
     * - System-level timestamp tracking
     * - Debugging creation order
     */
    @ColumnInfo(name = "created_date")
    override val createdDate: LocalDateTime = LocalDateTime.now()
) : BaseEntity() {

    /**
     * Check if patient has at least one contact method
     *
     * Business rule: Phone or email required.
     * Validation should happen at application layer before save.
     *
     * @return true if phone or email is not empty/null
     */
    fun hasContactInfo(): Boolean = !phone.isNullOrEmpty() || !email.isNullOrEmpty()

    /**
     * Check if patient is active
     *
     * @return true if status is ACTIVE
     */
    fun isActive(): Boolean = status == Constants.PatientStatus.ACTIVE.name

    /**
     * Check if patient is inactive
     *
     * @return true if status is INACTIVE
     */
    fun isInactive(): Boolean = !isActive()

    /**
     * Get patient full name for display
     *
     * @return Trimmed patient name
     */
    fun getDisplayName(): String = name.trim()

    /**
     * Get primary contact (phone preferred, falls back to email)
     *
     * @return Phone if available, otherwise email, otherwise null
     */
    fun getPrimaryContact(): String? = phone ?: email

    companion object {
        /**
         * Create a test patient entity
         *
         * Useful for testing and fixtures.
         *
         * @param id Entity ID (0 = unsaved)
         * @param name Patient name
         * @param phone Optional phone number
         * @param email Optional email address
         * @param status ACTIVE or INACTIVE
         * @return PatientEntity instance
         */
        fun createForTesting(
            id: Long = 0,
            name: String = "Test Patient",
            phone: String? = "(11) 99999-9999",
            email: String? = "test@example.com",
            status: String = Constants.PatientStatus.ACTIVE.name
        ): PatientEntity {
            val today = LocalDate.now()
            return PatientEntity(
                id = id,
                name = name,
                phone = phone,
                email = email,
                status = status,
                initialConsultDate = today,
                registrationDate = today,
                lastAppointmentDate = null,
                createdDate = LocalDateTime.now()
            )
        }
    }
}

/**
 * Extension to import Constants
 *
 * Provides access to PatientStatus enum from Constants.
 */
private object Constants {
    enum class PatientStatus {
        ACTIVE, INACTIVE
    }
}
